import os
Import('env')

files = ['memcmp', 'memcpy', 'memset', 'strcat', 'strcmp', 'strlen', 'strncat', 'strncmp']

objects = []

for curfile in files:
	# change to the proper file extension
	if os.path.isfile(curfile+'.S'):
		curfileext = curfile + '.S'
	else:
		curfileext = curfile + '$CFILESUFFIX'
	
	o = env.Object('#/objects/' + curfile + '.o', curfileext);
	objects.append(o)
	
Return('objects')
