import os
Import('env')

files = [ 'createentry_os', 'getfilesize_os', 'openfile_os', 'writefile_os', 'readfile_os', 'closefile_os',
 'getfilesize', 'openfile', 'writefile', 'readfile', 'closefile', 'createfile', 'createdirectory']

objects = []

for curfile in files:
	# change to the proper file extension
	if os.path.isfile(curfile+'.S'):
		curfileext = curfile + '.S'
	else:
		curfileext = curfile + '$CFILESUFFIX'
	
	o = env.Object('#/objects/' + curfile + '.o', curfileext);
	objects.append(o)
	
Return('objects')
